Github Action workflow base
eclipse-uprotocol/up-cpp pull request #35
Opened 2024-01-03 16:59 UTC by giorgiozoppi

Hello,
this is a skeleton CI workflow that allows to check if main is broken or not and ensure a minimal check coverage of 80 per cent. It's better of having nothing. As incremental we might add cppcheck and its custom rules for our use case both Misra/Autosar/cpp-core-guidelines to having better linted code,

2024-01-10 19:13 UTC, stevenhartley requested changes
@giorgiozoppi it appears that the majority of the commits you made are under the github email address that is not associated with the signed ECA. To fix this, go to your github account and then add your gm.com email address. The next day (not sure how long the cron job takes) recreate the PR with a single squashed commit and we can then take it from there. 

Thank you BTW for this!!!!

2024-01-10 19:14 UTC, stevenhartley commented on .github/workflows/build.yml
> +      run: |
We should not be forced to build protobuf but use conan to pull build recipes.

2024-01-10 22:21 UTC, giorgiozoppi commented
Ok. asap I've capacity I fix and help it out. Btw who is leading the rust effort?

2024-01-11 00:23 UTC, stevenhartley commented
Daniel and Kai (from Etas & Bosch)

On Wed, Jan 10, 2024 at 5:21 PM Giorgio Zoppi ***@***.***>
wrote:

> Ok. asap I've capacity I fix and help it out. Btw who is leading the rust
> effort?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eclipse-uprotocol/uprotocol-cpp/pull/35#issuecomment-1885835167>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACDANOT3QBMAZJCRW2CMVB3YN4H5ZAVCNFSM6AAAAABBLW27CKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOBVHAZTKMJWG4>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-01-31 22:07 UTC, giorgiozoppi commented
close this. reopening during with a consistent account.

2024-01-31 22:07 UTC, closed without merging