Change URI to Builder pattern
eclipse-uprotocol/up-cpp pull request #37
Opened 2024-01-21 09:39 UTC by adienzel

2024-01-22 10:31 UTC, xz62px requested changes

2024-01-22 10:31 UTC, xz62px commented on .gitignore
> +/uprotocol-core-api/
revert

2024-01-22 10:31 UTC, xz62px commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "${CAMKE_CXX_FLAGS} -g -L/usr/local/lib -I../ -pthread -Wall -Wpedantic")
revert

2024-01-22 10:31 UTC, xz62px commented on include/uprotocol-cpp/uri/builder/BuildEntity.h
> +#include "../uprotocol-core-api/src/main/proto/uri.pb.h"
should be #include <src/main/proto/uri.pb.h>

2024-01-22 10:31 UTC, xz62px commented on include/uprotocol-cpp/uri/builder/BuildEntity.h
> +#include "../tools/Utils.h"
should be #include<uprotocol-cpp/uri/tools/>

2024-01-22 10:31 UTC, xz62px commented on include/uprotocol-cpp/uri/builder/BuildUAuthority.h
> +#include "../tools/Utils.h"
same comments

2024-01-22 10:31 UTC, xz62px commented on include/uprotocol-cpp/uri/builder/BuildUResource.h
> +#include "../tools/Utils.h"
same comments

2024-01-22 10:31 UTC, xz62px commented on include/uprotocol-cpp/uri/datamodel/UUri.h
> +#include "../uprotocol-core-api/src/main/proto/uri.pb.h"
same comment

2024-01-22 10:31 UTC, xz62px commented on include/uprotocol-cpp/uri/datamodel/UUri.h
> +        //todo hash
Dont forget the dodo

2024-01-22 10:31 UTC, xz62px commented on include/uprotocol-cpp/uri/serializer/IpAddress.h
> +//            ipBytes_.push_back(ipByte);
delete if not needed

2024-01-22 10:31 UTC, xz62px commented on include/uprotocol-cpp/uri/serializer/IpAddress.h
> +    auto getString() const { return ipString_; }
we know the type , why use auto and not std::string?

2024-01-22 10:31 UTC, xz62px commented on include/uprotocol-cpp/uri/serializer/IpAddress.h
> +    static constexpr uint8_t IpV4AddressBytes = 4;
add _

2024-01-22 10:31 UTC, xz62px commented on include/uprotocol-cpp/uri/serializer/LongUriSerializer.h
> +    static auto serialize(const v1::UUri& u_uri) -> std::string;
same comment

2024-01-22 10:31 UTC, xz62px commented on include/uprotocol-cpp/uri/serializer/LongUriSerializer.h
> +#include "../uprotocol-core-api/src/main/proto/uri.pb.h"
please fix the includes

2024-01-22 10:31 UTC, xz62px commented on include/uprotocol-cpp/uri/serializer/MicroUriSerializer.h
> +    static constexpr uint32_t IpV4MicroUriLength = 12;
add _ to all

2024-01-22 10:31 UTC, xz62px commented on include/uprotocol-cpp/uri/serializer/MicroUriSerializer.h
> +
remove one space

2024-01-22 10:31 UTC, xz62px commented on include/uprotocol-cpp/uri/tools/Utils.h
> +
remove empty line and fix include

2024-01-22 10:31 UTC, xz62px commented on src/uri/LongUriSerializer.cpp
> +//using namespace uprotocol::uri;
delete if not needed

2024-01-22 10:31 UTC, xz62px commented on test/uri/builder/UAuthorityTest.cpp
> +#include <string>
please modify the test to gtest instead of cgreen

2024-01-22 10:31 UTC, xz62px commented on test/uri/builder/UEntityTest.cpp
> +#include <string>
please modify the test to gtest instead of cgreen

2024-01-22 10:31 UTC, xz62px commented on test/uri/builder/UUriTest.cpp
> +#include "uprotocol-cpp/uri/serializer/MicroUriSerializer.h"
please modify the test to gtest instead of cgreen

2024-01-29 16:40 UTC, closed without merging

2024-01-29 16:40 UTC, stevenhartley commented
Closing PR, will use @MelamudMichael branch instead