Creating a uAttributes Builder Class
eclipse-uprotocol/up-cpp pull request #40
Opened 2024-01-30 22:17 UTC by moniercoding

2024-02-18 06:42 UTC, MelamudMichael requested changes

2024-02-18 06:42 UTC, MelamudMichael commented on include/uprotocol-cpp/rpc/RpcClient.h
> +#include <uprotocol-cpp/transport/datamodel/UAttributesBuilder.h>
this include is not needed

2024-02-18 06:42 UTC, MelamudMichael commented on include/uprotocol-cpp/transport/datamodel/UAttributesBuilder.h
> +#include <memory>
please check if all of the includes are actually needed

2024-02-18 06:42 UTC, MelamudMichael commented on include/uprotocol-cpp/transport/datamodel/UAttributesBuilder.h
> +#include "up-core-api/uattributes.pb.h"
change to <>

2024-02-18 06:42 UTC, MelamudMichael commented on include/uprotocol-cpp/transport/datamodel/UAttributesBuilder.h
> +        UAttributesBuilder() {
you need also the constructor for the mandatory attributes 
            UAttributes(const UUID id,
                        const UMessageType type,
                        const UPriority priority) {

2024-02-18 06:42 UTC, MelamudMichael commented on include/uprotocol-cpp/transport/datamodel/UListener.h
> +#include <uprotocol-cpp/transport/datamodel/UAttributesBuilder.h>
not needed

2024-02-21 05:59 UTC, MelamudMichael requested changes
This PR is OK , but it should not be merged before the up-client PR is ready
did you run the unit-tests?

2024-02-28 20:08 UTC, stevenhartley commented
Why are we not moving to UAttributes to align with core-api 1.5.6?

2024-03-04 15:09 UTC, closed without merging

2024-03-04 15:09 UTC, moniercoding commented
Creating a new PR