Feature/adding thread pool
eclipse-uprotocol/up-cpp pull request #53
Opened 2024-02-12 10:01 UTC by MelamudMichael

2024-02-21 22:20 UTC, linsonittoop requested changes
Update the copyright in all modified files.

2024-02-21 22:20 UTC, linsonittoop commented on include/up-cpp/utils/CyclicQueue.h
> +		static constexpr std::chrono::milliseconds DefaultPopQueueTimeout { 5U };
Appending the unit in variable names would be helpful.

eg: DefaultPopQueueTimeoutMilllseconds or DefaultPopQueueTimeoutMs

2024-02-21 22:20 UTC, linsonittoop commented on include/up-cpp/utils/ThreadPool.h
> +        static constexpr auto timeout_ = 100;
Appending the unit in variable names would be helpful.

eg. timeoutSeconds_ or timeoutInSeconds_ or timeoutMilliseconds_

2024-02-26 15:18 UTC, stevenhartley approved these changes

2024-02-26 18:14 UTC, merged