Feature/support conan package creation from local build
eclipse-uprotocol/up-cpp pull request #90
Opened 2024-04-11 17:28 UTC by maxfaine

Feature/support conan package creation from local build

2024-04-11 23:44 UTC, gregmedd requested changes
I was able to build this library on a clean ubuntu 22.04 system by following the README. However, I was not able to subsequently build up-client-zenoh-cpp against it. Please make sure that it is possible to go from zenoh-c to up-cpp, up-client-zenoh-cpp, and finally up-zenoh-example-cpp with these changes in place.

Your CI failure is related to the update in the README - since `version = "0.1.1-dev"` was removed from conanfile.py, you will need to specify a version in [.github/workflows/ci.yml](https://github.com/eclipse-uprotocol/up-cpp/blob/main/.github/workflows/ci.yml).

Lastly, I'd like for you to update both the commits and this review with a meaningful description of what these changes are and what they do. The commits can be squashed and reworded however you best feel conveys the content of your work using git rebase -i ....

2024-04-11 23:44 UTC, gregmedd commented on conanfile.py
> +        "build_unbundled": True,
Why is it important to change the default? Does that change the build instructions in the README file?

2024-04-11 23:44 UTC, gregmedd commented on conanfile.py
> +            return
Do we have documentation for all of the variables (both environment and command line) that are taken by the build scripts? This should be added there with an explanation of what it is, what it does, and how to set it.

2024-04-11 23:44 UTC, gregmedd commented on conanfile.py
> +            self.cpp_info.libs = ["up-cpp"]
These are fairly significant changes. Can you provide an explanation of what these changes are and what they do?

2024-04-12 00:52 UTC, stevenhartley commented
> I was able to build this library on a clean ubuntu 22.04 system by following the README. However, I was not able to subsequently build up-client-zenoh-cpp against it. Please make sure that it is possible to go from zenoh-c to up-cpp, up-client-zenoh-cpp, and finally up-zenoh-example-cpp with these changes in place.
> 
> Your CI failure is related to the update in the README - since `version = "0.1.1-dev"` was removed from conanfile.py, you will need to specify a version in [.github/workflows/ci.yml](https://github.com/eclipse-uprotocol/up-cpp/blob/main/.github/workflows/ci.yml).
> 
> Lastly, I'd like for you to update both the commits and this review with a meaningful description of what these changes are and what they do. The commits can be squashed and reworded however you best feel conveys the content of your work using git rebase -i ....

We should probably not specify version in the ci workflow as this is difficult to maintain but leverage conan to build and pull the right dependencies. Maybe git submodules or we push to conan central.

2024-05-23 22:35 UTC, gregmedd commented
Closing stale PRs. We are tracking conan recipes on the project board.

2024-05-23 22:35 UTC, closed without merging