Separated conan responsibility into build vs package
eclipse-uprotocol/up-cpp pull request #96
Opened 2024-04-18 03:23 UTC by PLeVasseur

# What

Separated conan responsibility into build vs package:
* `./conan-recipes/conanfile.py` contains the conan recipe to package
* `./conanfile.py` will install dependencies & build

Update README.md to reflect these changes.

# Why

We want to support local builds & packaging.

# Next Steps

We also want to separately create an entry into [Conan Center Index](https://github.com/conan-io/conan-center-index) to support pulling `up-cpp` packages directly for users.

2024-04-18 11:28 UTC, stevenhartley requested changes
@PLeVasseur you need to fix/update the ci workflows with the changes to the build instructions, otherwise the workflows will fail and we cannot merge the change

2024-04-18 12:57 UTC, PLeVasseur commented
Pause on this while I update the GitHub workflow a little more

2024-04-18 12:59 UTC, PLeVasseur commented on .github/workflows/ci.yml
> +  package:
@stevenhartley, @gregmedd -- FYI I updated to separate out the test vs package flows to distinguish between them and their conanfile.py

2024-04-18 12:59 UTC, PLeVasseur commented on .github/workflows/ci.yml
> +    needs: [test, package]
Depending on the new package flow as well

2024-04-18 15:01 UTC, PLeVasseur commented
> Pause on this while I update the GitHub workflow a little more

OK -- should be good for review :slightly_smiling_face:

2024-04-18 19:28 UTC, stevenhartley commented on conanfile_package.py
why rename and not in separate file (out of curiosity)?

2024-04-18 19:41 UTC, PLeVasseur commented on conanfile_package.py
Good question!

I tried to put it in `conan-recipes`, but seems like Conan forbids you from using ".." to hop out of the folder for security reasons.

So this was the next best alternative I found.

2024-04-19 18:12 UTC, PLeVasseur commented
Putting this in draft status while I try to work out the kinks a little more.

Next goal:
* version which works for local build & package
* version which can be put into CCI

2024-04-19 22:01 UTC, PLeVasseur commented
@stevenhartley -- broke out into a conanfile.py we can use for local builds & packaging and another one under the ./conan-recipes/cci that we can use for uploading to CCI.

Both work and have workflows added for them.

Need to open a PR over to CCI and see what else may be wrong with the CCI one.

2024-04-22 20:14 UTC, PLeVasseur commented
> Putting this in draft status while I try to work out the kinks a little more.
> 
> Next goal:
> 
> * version which works for local build & package
> * version which can be put into CCI

Well Conan the package manager has the perfect tool for the use case I'm considering of sharing packaging instructions between the CCI recipe and local build recipe: python requires

However, recipes hosted on CCI are banned from using it :upside_down_face: 

https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#are-python-requires-allowed-in-the-conan-center-index

Given that path is a dead-end I tried to inherit from the CCI recipe, but that's looking like it's tricky as well, because the relative paths between the CCI recipe and the local one are not maintained when copied into the Conan cache (`~/.conan2`).

Based on that, I'm considering the current form of this PR to be ~ reasonable enough ~ where-in we have 2 x recipes, one for CCI packaging and one for local build & package without doing anything fancy to share code.

WDYT @stevenhartley, @gregmedd ?

2024-04-24 13:49 UTC, PLeVasseur commented
FYI all -- I submitted the package to CCI, waiting to hear feedback and reflect that into the one we'll maintain in the repo.

2024-05-23 22:36 UTC, gregmedd commented
Closing stale PRs. We are tracking conan recipes on the project board.

2024-05-23 22:36 UTC, closed without merging